apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gs-inv-media-pvc
  labels:
    app.kubernetes.io/name: gs-inv-mgmt
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 100Gi
