apiVersion: v1
kind: Secret
metadata:
  name: gs-inv-secret
  labels:
    app.kubernetes.io/name: gs-inv-mgmt
    env: prod
type: Opaque
stringData:
  DB_AUTO_MIGRATE: "false"
  POSTGRES_HOST: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  APP_AUTH_SIGNING_KEY: ""
  APP_REQUIRE_PASSWORD_AUTH: "true"
  APP_AUTH_REMEMBER_DAYS: "30"
  APP_AUTH_COOKIE_ENABLED: "false"
  EBAY_ENVIRONMENT: production
  EBAY_CLIENT_ID: ""
  EBAY_CLIENT_SECRET: ""
  EBAY_RU_NAME: ""
  EBAY_REDIRECT_URI: ""
  EBAY_USER_ACCESS_TOKEN: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET: ""
  S3_ENDPOINT_URL: ""
  S3_PUBLIC_BASE_URL: ""
