from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal, InvalidOperation
import hashlib
import json
from typing import Any


@dataclass(frozen=True)
class QuickBooksClearingConfig:
    clearing_account_ref: str = "Custom App Clearing Account"
    sales_income_account_ref: str = "Marketplace Sales"
    shipping_income_account_ref: str = "Shipping Income"
    ebay_customer_ref: str = "eBay Sales Customer"
    ebay_vendor_ref: str = "eBay Vendor"
    ebay_payment_method_ref: str = "eBay Payout"
    ebay_fee_expense_account_ref: str = "Merchant Account Fees"
    ebay_shipping_expense_account_ref: str = "eBay Shipping Expense"
    ebay_subscription_expense_account_ref: str = "eBay Subscription Expense"
    ebay_adjustment_expense_account_ref: str = "Bank Charges & Fees"
    tax_code_ref: str = "NON"
    doc_number_prefix: str = "GS"


def _field(row: Any, *names: str, default: Any = None) -> Any:
    if isinstance(row, dict):
        for name in names:
            if name in row and row.get(name) is not None:
                return row.get(name)
        return default
    for name in names:
        value = getattr(row, name, None)
        if value is not None:
            return value
    return default


def _money(value: Any) -> str:
    try:
        amount = Decimal(str(value if value is not None else "0"))
    except (InvalidOperation, ValueError):
        amount = Decimal("0")
    return f"{amount.quantize(Decimal('0.01'))}"


def _int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _date_text(value: Any) -> str:
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    text = str(value or "").strip()
    if not text:
        return date.today().isoformat()
    if "T" in text:
        text = text.split("T", 1)[0]
    return text[:10]


def _ref(value: str) -> dict[str, str]:
    clean = str(value or "").strip()
    return {"value": clean}


def _doc_number(prefix: str, kind: str, source_id: Any) -> str:
    raw_source = str(source_id or "").strip() or "unknown"
    raw = f"{prefix}-{kind}-{raw_source}"
    if len(raw) <= 21:
        return raw
    digest = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:8].upper()
    return f"{prefix}-{kind[:3]}-{digest}"[:21]


def quickbooks_sales_receipt_payload(
    sale: Any,
    *,
    config: QuickBooksClearingConfig | None = None,
) -> dict[str, Any]:
    cfg = config or QuickBooksClearingConfig()
    source_id = _field(sale, "external_order_id", "order_id", "sale_id", "id", default="")
    quantity = max(1, _int(_field(sale, "quantity_sold", "quantity", "qty", default=1), 1))
    gross_total = Decimal(_money(_field(sale, "gross_amount", "gross_sales", "amount", "total", default="0")))
    unit_price = gross_total / Decimal(quantity)
    sku = str(_field(sale, "sku", "product_sku", "item_ref", default="")).strip()

    return {
        "DocNumber": _doc_number(cfg.doc_number_prefix, "SALE", source_id),
        "TxnDate": _date_text(_field(sale, "transaction_date", "sold_at", "created_at", default=None)),
        "CustomerRef": _ref(cfg.ebay_customer_ref),
        "PaymentMethodRef": _ref(cfg.ebay_payment_method_ref),
        "DepositToAccountRef": _ref(cfg.clearing_account_ref),
        "Line": [
            {
                "DetailType": "SalesItemLineDetail",
                "Amount": _money(gross_total),
                "SalesItemLineDetail": {
                    "ItemRef": _ref(sku),
                    "Qty": quantity,
                    "UnitPrice": _money(unit_price),
                    "TaxCodeRef": _ref(cfg.tax_code_ref),
                },
            }
        ],
        "PrivateNote": "Generated by GoldenStackers app using clearing-account workflow.",
    }


def quickbooks_order_fee_purchase_payload(
    fee: Any,
    *,
    config: QuickBooksClearingConfig | None = None,
) -> dict[str, Any]:
    cfg = config or QuickBooksClearingConfig()
    source_id = _field(fee, "external_order_id", "order_id", "sale_id", "id", default="")
    return {
        "DocNumber": _doc_number(cfg.doc_number_prefix, "FEE", source_id),
        "TxnDate": _date_text(_field(fee, "fee_date", "transaction_date", "sold_at", "created_at", default=None)),
        "AccountRef": _ref(cfg.clearing_account_ref),
        "EntityRef": _ref(cfg.ebay_vendor_ref),
        "PaymentType": "Cash",
        "Line": [
            {
                "DetailType": "AccountBasedExpenseLineDetail",
                "Amount": _money(_field(fee, "fee_amount", "fees", "fee_total", default="0")),
                "AccountBasedExpenseLineDetail": {
                    "AccountRef": _ref(cfg.ebay_fee_expense_account_ref),
                },
            }
        ],
        "PrivateNote": "Generated by GoldenStackers app for eBay order fees via clearing account.",
    }


def quickbooks_non_order_fee_purchase_payload(
    adjustment: Any,
    *,
    config: QuickBooksClearingConfig | None = None,
) -> dict[str, Any]:
    cfg = config or QuickBooksClearingConfig()
    fee_type = str(_field(adjustment, "fee_type", "type", "category", default="adjustment") or "").strip().lower()
    if "ship" in fee_type or "label" in fee_type:
        expense_account = cfg.ebay_shipping_expense_account_ref
    elif "subscription" in fee_type or "store" in fee_type:
        expense_account = cfg.ebay_subscription_expense_account_ref
    else:
        expense_account = cfg.ebay_adjustment_expense_account_ref
    source_id = _field(adjustment, "external_id", "payout_id", "id", default=fee_type)
    return {
        "DocNumber": _doc_number(cfg.doc_number_prefix, "ADJ", source_id),
        "TxnDate": _date_text(_field(adjustment, "fee_date", "transaction_date", "created_at", default=None)),
        "AccountRef": _ref(cfg.clearing_account_ref),
        "EntityRef": _ref(cfg.ebay_vendor_ref),
        "PaymentType": "Cash",
        "Line": [
            {
                "DetailType": "AccountBasedExpenseLineDetail",
                "Amount": _money(_field(adjustment, "amount", "fee_amount", "total", default="0")),
                "AccountBasedExpenseLineDetail": {
                    "AccountRef": _ref(expense_account),
                },
            }
        ],
        "PrivateNote": f"Generated by GoldenStackers app for eBay payout {fee_type or 'adjustment'} via clearing account.",
    }


def quickbooks_config_from_runtime(repo: Any) -> QuickBooksClearingConfig:
    from app.services.runtime_settings import get_runtime_str

    defaults = QuickBooksClearingConfig()
    return QuickBooksClearingConfig(
        clearing_account_ref=get_runtime_str(
            repo, "quickbooks_clearing_account_ref", defaults.clearing_account_ref
        ).strip(),
        sales_income_account_ref=get_runtime_str(
            repo, "quickbooks_sales_income_account_ref", defaults.sales_income_account_ref
        ).strip(),
        shipping_income_account_ref=get_runtime_str(
            repo, "quickbooks_shipping_income_account_ref", defaults.shipping_income_account_ref
        ).strip(),
        ebay_customer_ref=get_runtime_str(repo, "quickbooks_ebay_customer_ref", defaults.ebay_customer_ref).strip(),
        ebay_vendor_ref=get_runtime_str(repo, "quickbooks_ebay_vendor_ref", defaults.ebay_vendor_ref).strip(),
        ebay_payment_method_ref=get_runtime_str(
            repo, "quickbooks_ebay_payment_method_ref", defaults.ebay_payment_method_ref
        ).strip(),
        ebay_fee_expense_account_ref=get_runtime_str(
            repo, "quickbooks_ebay_fee_expense_account_ref", defaults.ebay_fee_expense_account_ref
        ).strip(),
        ebay_shipping_expense_account_ref=get_runtime_str(
            repo, "quickbooks_ebay_shipping_expense_account_ref", defaults.ebay_shipping_expense_account_ref
        ).strip(),
        ebay_subscription_expense_account_ref=get_runtime_str(
            repo, "quickbooks_ebay_subscription_expense_account_ref", defaults.ebay_subscription_expense_account_ref
        ).strip(),
        ebay_adjustment_expense_account_ref=get_runtime_str(
            repo, "quickbooks_ebay_adjustment_expense_account_ref", defaults.ebay_adjustment_expense_account_ref
        ).strip(),
        tax_code_ref=get_runtime_str(repo, "quickbooks_tax_code_ref", defaults.tax_code_ref).strip(),
        doc_number_prefix=get_runtime_str(repo, "quickbooks_doc_number_prefix", defaults.doc_number_prefix).strip()
        or defaults.doc_number_prefix,
    )


def quickbooks_payload_validation_issues(payload: dict[str, Any]) -> list[str]:
    issues: list[str] = []
    if not str(payload.get("DocNumber") or "").strip():
        issues.append("missing_doc_number")
    if not str(payload.get("TxnDate") or "").strip():
        issues.append("missing_txn_date")
    for ref_key in ("CustomerRef", "DepositToAccountRef", "AccountRef", "EntityRef"):
        ref = payload.get(ref_key)
        if ref is not None and not str((ref or {}).get("value") or "").strip():
            issues.append(f"missing_{ref_key.lower()}")
    for index, line in enumerate(payload.get("Line") or []):
        detail_type = str(line.get("DetailType") or "").strip()
        if not detail_type:
            issues.append(f"line_{index}_missing_detail_type")
        if Decimal(_money(line.get("Amount"))) <= 0:
            issues.append(f"line_{index}_nonpositive_amount")
        detail = line.get(detail_type) or {}
        item_ref = detail.get("ItemRef")
        account_ref = detail.get("AccountRef")
        if item_ref is not None and not str((item_ref or {}).get("value") or "").strip():
            issues.append(f"line_{index}_missing_item_ref")
        if account_ref is not None and not str((account_ref or {}).get("value") or "").strip():
            issues.append(f"line_{index}_missing_expense_account_ref")
    return issues


def quickbooks_rows_from_actual_economics(actual_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for row in actual_rows or []:
        sale_id = _field(row, "sale_id", "id", default="")
        sold_at = _field(row, "sold_at", "transaction_date", "created_at", default="")
        doc_number = str(_field(row, "external_order_id", "doc_number", default="") or "").strip()
        if not doc_number:
            doc_number = f"SALE-{sale_id or 'unknown'}"
        rows.append(
            {
                "txn_date": _date_text(sold_at),
                "doc_number": doc_number,
                "sale_id": sale_id,
                "marketplace": str(_field(row, "marketplace", default="") or "").strip().lower(),
                "item_sku": str(_field(row, "sku", "item_sku", default="") or "").strip(),
                "item_description": str(_field(row, "product_title", "item_description", default="") or "").strip(),
                "quantity": max(1, _int(_field(row, "qty", "quantity", "quantity_sold", default=1), 1)),
                "amount": _money(_field(row, "sold_price", "gross_sales", "amount", default="0")),
                "fees": _money(_field(row, "allocated_fee_actual", "fees", default="0")),
                "fee_source": str(_field(row, "actual_fee_source", "fee_source", default="") or "").strip(),
                "shipping_cost": _money(
                    _field(row, "allocated_shipping_charged", "shipping_cost", default="0")
                ),
                "shipping_label_cost": _money(
                    _field(row, "allocated_shipping_actual", "shipping_label_cost", default="0")
                ),
                "shipping_label_source": str(
                    _field(row, "actual_shipping_source", "shipping_label_source", default="") or ""
                ).strip(),
            }
        )
    return rows


def quickbooks_payload_preview_records(
    qbo_rows: list[dict[str, Any]],
    *,
    config: QuickBooksClearingConfig | None = None,
) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for row in qbo_rows or []:
        source_doc = str(_field(row, "doc_number", default="") or "").strip()
        sale_payload = quickbooks_sales_receipt_payload(
            {
                "external_order_id": source_doc,
                "sold_at": _field(row, "txn_date", default=""),
                "sku": _field(row, "item_sku", default=""),
                "quantity_sold": _field(row, "quantity", default=1),
                "gross_amount": _field(row, "amount", default="0"),
            },
            config=config,
        )
        records.append(_preview_record("SalesReceipt", source_doc, "sales_receipt", sale_payload))

        fee_amount = Decimal(_money(_field(row, "fees", default="0")))
        if fee_amount > 0:
            fee_payload = quickbooks_order_fee_purchase_payload(
                {
                    "external_order_id": source_doc,
                    "fee_date": _field(row, "txn_date", default=""),
                    "fee_amount": fee_amount,
                },
                config=config,
            )
            records.append(_preview_record("Purchase", source_doc, "order_fee_purchase", fee_payload))

        label_amount = Decimal(_money(_field(row, "shipping_label_cost", default="0")))
        if label_amount > 0:
            label_payload = quickbooks_non_order_fee_purchase_payload(
                {
                    "external_id": f"{source_doc or 'unknown'}-SHIP",
                    "fee_type": "shipping_label",
                    "fee_date": _field(row, "txn_date", default=""),
                    "amount": label_amount,
                },
                config=config,
            )
            records.append(_preview_record("Purchase", source_doc, "shipping_label_purchase", label_payload))
    return records


def quickbooks_manual_journal_packet(
    actual_rows: list[dict[str, Any]],
    *,
    config: QuickBooksClearingConfig | None = None,
    period_label: str = "",
) -> dict[str, Any]:
    cfg = config or QuickBooksClearingConfig()
    qbo_rows = quickbooks_rows_from_actual_economics(actual_rows)
    gross_sales = sum((Decimal(_money(_field(row, "amount", default="0"))) for row in qbo_rows), Decimal("0"))
    shipping_charged = sum(
        (Decimal(_money(_field(row, "shipping_cost", default="0"))) for row in qbo_rows), Decimal("0")
    )
    ebay_fees = sum((Decimal(_money(_field(row, "fees", default="0"))) for row in qbo_rows), Decimal("0"))
    label_spend = sum(
        (Decimal(_money(_field(row, "shipping_label_cost", default="0"))) for row in qbo_rows), Decimal("0")
    )
    income_receivable = gross_sales + shipping_charged
    marketplace_deductions = ebay_fees + label_spend
    expected_net_payout = income_receivable - marketplace_deductions

    journal_rows: list[dict[str, Any]] = []

    def add_row(
        *,
        line_no: int,
        account_ref: str,
        debit: Decimal = Decimal("0"),
        credit: Decimal = Decimal("0"),
        memo: str,
        source: str,
    ) -> None:
        if debit <= 0 and credit <= 0:
            return
        journal_rows.append(
            {
                "line_no": line_no,
                "account_ref": account_ref,
                "debit": _money(debit),
                "credit": _money(credit),
                "memo": memo,
                "source": source,
            }
        )

    label = f" for {period_label}" if str(period_label or "").strip() else ""
    add_row(
        line_no=1,
        account_ref=cfg.clearing_account_ref,
        debit=income_receivable,
        memo=f"Record gross eBay receivable{label}: item sales plus buyer-paid shipping.",
        source="gross_sales_plus_shipping_charged",
    )
    add_row(
        line_no=2,
        account_ref=cfg.sales_income_account_ref,
        credit=gross_sales,
        memo=f"Record eBay gross item sales{label}.",
        source="gross_sales",
    )
    add_row(
        line_no=3,
        account_ref=cfg.shipping_income_account_ref,
        credit=shipping_charged,
        memo=f"Record buyer-paid shipping charged through eBay{label}.",
        source="shipping_charged",
    )
    add_row(
        line_no=4,
        account_ref=cfg.ebay_fee_expense_account_ref,
        debit=ebay_fees,
        memo=f"Record eBay order-level marketplace fees{label}.",
        source="ebay_fees",
    )
    add_row(
        line_no=5,
        account_ref=cfg.ebay_shipping_expense_account_ref,
        debit=label_spend,
        memo=f"Record eBay/marketplace shipping-label spend{label}.",
        source="shipping_label_spend",
    )
    add_row(
        line_no=6,
        account_ref=cfg.clearing_account_ref,
        credit=marketplace_deductions,
        memo=f"Reduce clearing account for eBay fees and shipping-label deductions{label}.",
        source="marketplace_deductions",
    )

    total_debits = sum((Decimal(row["debit"]) for row in journal_rows), Decimal("0"))
    total_credits = sum((Decimal(row["credit"]) for row in journal_rows), Decimal("0"))
    summary = {
        "period_label": str(period_label or "").strip(),
        "source_rows": len(qbo_rows),
        "gross_sales": _money(gross_sales),
        "shipping_charged": _money(shipping_charged),
        "income_receivable": _money(income_receivable),
        "ebay_fees": _money(ebay_fees),
        "shipping_label_spend": _money(label_spend),
        "marketplace_deductions": _money(marketplace_deductions),
        "expected_net_payout": _money(expected_net_payout),
        "total_debits": _money(total_debits),
        "total_credits": _money(total_credits),
        "out_of_balance": _money(total_debits - total_credits),
    }
    packet = {"summary": summary, "journal_rows": journal_rows}
    packet["evidence_sha256"] = hashlib.sha256(json.dumps(packet, sort_keys=True).encode("utf-8")).hexdigest()
    return packet


def _preview_record(
    payload_type: str,
    source_doc_number: str,
    action: str,
    payload: dict[str, Any],
) -> dict[str, Any]:
    issues = quickbooks_payload_validation_issues(payload)
    return {
        "payload_type": payload_type,
        "action": action,
        "source_doc_number": str(source_doc_number or "").strip(),
        "qbo_doc_number": str(payload.get("DocNumber") or "").strip(),
        "validation_status": "ok" if not issues else "review",
        "validation_issues": issues,
        "payload_sha256": hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest(),
        "payload": payload,
    }
