apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gs-inv-media-pvc
  labels:
    app.kubernetes.io/name: gs-inv-mgmt
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
