apiVersion: v1
kind: Secret
metadata:
  name: gs-inv-secret
type: Opaque
stringData:
  DB_AUTO_MIGRATE: "false"
  POSTGRES_HOST: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  EBAY_ENVIRONMENT: sandbox
  EBAY_CLIENT_ID: ""
  EBAY_CLIENT_SECRET: ""
  EBAY_RU_NAME: ""
  EBAY_REDIRECT_URI: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET: ""
  S3_ENDPOINT_URL: ""
  S3_PUBLIC_BASE_URL: ""
