namespace: gs-inv-dev
resources:
  - ../../base
  - ingress.yaml
patchesStrategicMerge:
  - patch-configmap.yaml
  - patch-deployment.yaml
images:
  - name: ghcr.io/goldenstackers/gs-inv-mgmt
    newTag: dev
